### ISSUE TITLE
Repeating Data Changes ViewHolder Values On Scroll

### ISSUE THREAD

**Issue by Ankit-Khachane** [pankaj89/SimplerRecyclerViewAdapter#1]
I Tried Running The Sample Project On My Phone with some changes On **getDummyList**() method
i repeated the same entire set of add methods multiple time  and run the app, it was running the app but when i started scrolling the few **Viewholder Changes it's Data on Scrolling,** i found this issue, please try to avoid that.

**Comment by pankaj89** [comment]
Hello, Thanks for your input, Issue is now resolved in version 1.1

You can now use gradle as 
```
compile 'com.master.android:simpler-recycler-view-adapter:1.1'
```
Also there are some changes in ViewHolder Structures you can check it out here [Creating ViewHolder](..#creating-view-holder)

Thanks
Happy coding :)
